const express = require('express');
const router = express.Router();
const c = require('../controllers/reportsController');
const { authenticate, authorize } = require('../middleware/auth');
router.use(authenticate);
router.get('/members', authorize('admin', 'pastor', 'director'), c.getMemberReport);
router.get('/finance', authorize('admin', 'pastor', 'finance'), c.getFinanceReport);
router.get('/attendance', authorize('admin', 'pastor', 'director', 'hod'), c.getAttendanceReport);
router.get('/first-timers', authorize('admin', 'pastor', 'director'), c.getFirstTimerReport);
module.exports = router;
