const express = require('express');
const router = express.Router();
const c = require('../controllers/usersController');
const { authenticate, authorize } = require('../middleware/auth');
router.use(authenticate);
router.get('/', authorize('head_pastor','pastor'), c.getUsers);
router.post('/', authorize('head_pastor','pastor'), c.inviteUser);
router.put('/:id', authorize('head_pastor','pastor'), c.updateUser);
router.post('/:id/reset-password', authorize('head_pastor','pastor'), c.resetUserPassword);
module.exports = router;
